<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PackageId>RectangleF</PackageId>
    <Version>5.0.1</Version>
    <Title>RectangleF</Title>
    <Authors>dmanning23</Authors>
    <description>Simple MonoGame library for a rectangle that uses float values instead of int</description>
    <PackageProjectUrl>https://github.com/dmanning23/RectangleF</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/dmanning23/RectangleF</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>monogame</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.*">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>